# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [36]:
import numpy as np





### 2. Print the NUMPY version and the configuration.


In [37]:
pip --version


pip 26.1.2 from c:\Users\Shrabani P\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip (python 3.12)

Note: you may need to restart the kernel to use updated packages.


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [38]:
### with Random decimal numbers between 0 and 1

a = np.random.random((2,3,5))
print(a)


[[[0.48165436 0.22646646 0.52211076 0.85894912 0.87206355]
  [0.80070111 0.61636768 0.4080437  0.52016573 0.3854188 ]
  [0.88315837 0.34114886 0.72509505 0.04195734 0.83740149]]

 [[0.78666809 0.90538808 0.47768177 0.44306373 0.14415247]
  [0.72471426 0.05935973 0.77401614 0.1356971  0.16784484]
  [0.83825004 0.15872874 0.28257916 0.10113437 0.3040269 ]]]



### 4. Print a.


In [39]:
## matrix with random numbers between 1 to 100:
a=np.random.randint(1,100, size=(2,3,5))
print(a)


[[[ 5 86 21 93 31]
  [ 2 19 84 63 93]
  [11 51 90 22 15]]

 [[34 61 27 32  3]
  [81 17 76 24 85]
  [16 91 73 83 13]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [40]:
import numpy as np

b = np.ones((5,2,3))
print(b)



[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 6. Print b.


In [41]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [42]:
a_shape =np.shape(a)
b_shape=np.shape(b)

print(a_shape)
print(b_shape)


(2, 3, 5)
(5, 2, 3)


In [43]:
print(a.size)
print(b.size)

30
30


### yes, a and b have the same size but the the shapes are different. 


### 8. Are you able to add a and b? Why or why not?


### No, I cannot add matrices (or NumPy arrays) with shapes (2, 3, 5) and (5, 2, 3).

# Why?

For matrix/array addition, the dimensions must be exactly the same. But the shapes are:

a_shape = (2, 3, 5), 
b_shape = (5, 2, 3)

so I can not add these matrices.



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [44]:
### transpose of matrix b

c = b.transpose(1,2,0)

print(c)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [45]:
a_shape =np.shape(a)
c_shape =np.shape(c)

print(a_shape)
print(c_shape)

(2, 3, 5)
(2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [46]:

d = np.add(a,c)
print(d)

[[[ 6. 87. 22. 94. 32.]
  [ 3. 20. 85. 64. 94.]
  [12. 52. 91. 23. 16.]]

 [[35. 62. 28. 33.  4.]
  [82. 18. 77. 25. 86.]
  [17. 92. 74. 84. 14.]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [47]:
print(a)




[[[ 5 86 21 93 31]
  [ 2 19 84 63 93]
  [11 51 90 22 15]]

 [[34 61 27 32  3]
  [81 17 76 24 85]
  [16 91 73 83 13]]]


In [48]:
print(d)

[[[ 6. 87. 22. 94. 32.]
  [ 3. 20. 85. 64. 94.]
  [12. 52. 91. 23. 16.]]

 [[35. 62. 28. 33.  4.]
  [82. 18. 77. 25. 86.]
  [17. 92. 74. 84. 14.]]]


### Mathematically:

d=a+1

In [49]:
### If I do

print(d - a)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


# which confirms: d = a + 1


### 12. Multiply a and c. Assign the result to e.


In [50]:
print(a_shape)

print(c_shape)


(2, 3, 5)
(2, 3, 5)


In [51]:
e = a*c

print(e)

[[[ 5. 86. 21. 93. 31.]
  [ 2. 19. 84. 63. 93.]
  [11. 51. 90. 22. 15.]]

 [[34. 61. 27. 32.  3.]
  [81. 17. 76. 24. 85.]
  [16. 91. 73. 83. 13.]]]




### 13. Does e equal to a? Why or why not?


## Yes, both matrices e and a are equal. As the c matrix contains only 1 value, so after multiplication, the matrix is same.



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [52]:
d_max =np.max(d)

d_min =np.min(d)

d_mean = np.mean(d)


print(d_max)
print(d_min)

print(d_mean)




94.0
3.0
47.733333333333334



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [53]:
import numpy as np

f = np.empty((2, 3, 5))
print(f)


[[[ 5. 86. 21. 93. 31.]
  [ 2. 19. 84. 63. 93.]
  [11. 51. 90. 22. 15.]]

 [[34. 61. 27. 32.  3.]
  [81. 17. 76. 24. 85.]
  [16. 91. 73. 83. 13.]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [57]:
for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):

            if d[i][j][k] == d_min:
                f[i][j][k] = 0

            elif d[i][j][k] == d_max:
                f[i][j][k] = 100

            elif d[i][j][k] == d_mean:
                f[i][j][k] = 50

            elif d_min < d[i][j][k] < d_mean:
                f[i][j][k] = 25

            elif d_mean < d[i][j][k] < d_max:
                f[i][j][k] = 75


In [58]:
print(f)

[[[ 25.  75.  25. 100.  25.]
  [  0.  25.  75.  75. 100.]
  [ 25.  75.  75.  25.  25.]]

 [[ 25.  75.  25.  25.  25.]
  [ 75.  25.  75.  25.  75.]
  [ 25.  75.  75.  75.  25.]]]


In [59]:
print(d)

[[[ 6. 87. 22. 94. 32.]
  [ 3. 20. 85. 64. 94.]
  [12. 52. 91. 23. 16.]]

 [[35. 62. 28. 33.  4.]
  [82. 18. 77. 25. 86.]
  [17. 92. 74. 84. 14.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [60]:
print(d)


[[[ 6. 87. 22. 94. 32.]
  [ 3. 20. 85. 64. 94.]
  [12. 52. 91. 23. 16.]]

 [[35. 62. 28. 33.  4.]
  [82. 18. 77. 25. 86.]
  [17. 92. 74. 84. 14.]]]


In [61]:
print(f)

[[[ 25.  75.  25. 100.  25.]
  [  0.  25.  75.  75. 100.]
  [ 25.  75.  75.  25.  25.]]

 [[ 25.  75.  25.  25.  25.]
  [ 75.  25.  75.  25.  75.]
  [ 25.  75.  75.  75.  25.]]]


In [62]:
print(d_mean)

47.733333333333334


In [63]:
import numpy as np

if np.any(d == d_mean):
    print("50 will appear in f")
else:
    print("50 will NOT appear in f")

50 will NOT appear in f


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [66]:
f = [[['' for k in range(5)] for j in range(3)] for i in range(2)]

for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):

            value = d[i][j][k]

            if value == d_min:
                f[i][j][k] = 'A'
            elif d_min < value < d_mean:
                f[i][j][k] = 'B'
            elif value == d_mean:
                f[i][j][k] = 'C'
            elif d_mean < value < d_max:
                f[i][j][k] = 'D'
            elif value == d_max:
                f[i][j][k] = 'E'


print(f)

[[['B', 'D', 'B', 'E', 'B'], ['A', 'B', 'D', 'D', 'E'], ['B', 'D', 'D', 'B', 'B']], [['B', 'D', 'B', 'B', 'B'], ['D', 'B', 'D', 'B', 'D'], ['B', 'D', 'D', 'D', 'B']]]
